// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavegacinTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navegacin() {
    driver.get("http://localhost:8181/");
    driver.manage().window().setSize(new Dimension(1080, 819));
    assertThat(driver.getTitle(), is("Entorno de pruebas Web4Testing"));
    driver.findElement(By.linkText("Calculadora")).click();
    assertThat(driver.findElement(By.linkText("Calculadora")).getText(), is("Calculadora"));
    driver.findElement(By.linkText("Compras")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Compras"));
    driver.findElement(By.linkText("Contactos")).click();
    assertThat(driver.getTitle(), is("Contactos"));
    driver.findElement(By.linkText("Alertas")).click();
    assertThat(driver.findElement(By.cssSelector("h1:nth-child(1)")).getText(), is("Alertas"));
    driver.findElement(By.linkText("Ficheros")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Subir ficheros"));
    driver.findElement(By.linkText("APIs")).click();
    assertThat(driver.getTitle(), is("API REST"));
    driver.findElement(By.cssSelector(".fa-info-circle")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "Web4Testing"));
    }
  }
}
